### ISSUE TITLE
建议引入 coverage 保证测试覆盖率

### ISSUE THREAD

**Issue by Snoopy1866** [Xiaokang2022/maliang#48]
### Feature Description

以下两个工具可供参考：
- [pytest-cov](https://github.com/pytest-dev/pytest-cov) 用于生成测试覆盖率报告
- [codecov](https://github.com/apps/codecov) 用于分析测试覆盖率报告

codecov 对于公共仓库也是没有使用限制的。https://about.codecov.io/pricing/

### Possible Implementation

1. 工作流改进（参考 https://docs.codecov.com/docs/quick-start#step-4-upload-coverage-reports-to-codecov ）：
   ```
   - name: Test with pytest
      run: pytest --cov --cov-report=xml
   - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
   ```
2. 添加一个 bot，在 pr 上显示测试覆盖率报告，便于有针对性地补充测试代码。
3. 配置 `codecov.yml`（可选，参考 https://docs.codecov.com/docs/github-3-customizing-codecov ）
   取决于是否有强迫症，必须 100% 覆盖，默认情况下，如果不是 100% 覆盖，commit 会显示工作流运行失败（也可以设置只在 pr 上运行）。

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xiaokang2022** [comment]
~~等测试代码写的差不多的时候就加，现在测试还有很多没有写完，加了也必是失败（我强迫症玩家，要 100%）~~  
就是懒而已 :)

**Comment by Snoopy1866** [comment]
重新看了一遍 coverage 文档，发现通过输出 `junitxml` 可以直接在 PR 页面显示 pytest 的错误输出。
https://docs.codecov.com/docs/test-analytics

只需要在 workflow 最后加上一段：

```yaml
- name: Upload test results to Codecov
      	if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```

<details><summary>展开</summary>

![image](https://github.com/user-attachments/assets/03fa0167-9a7e-4bce-8560-249b7139eb88)
</details>
